teset:
	gcc design_code.c -o design_code
	echo "********start to run design_code.exe******"
	design_code.exe
	echo "********end to run design_code.exe******"

	gcc design_float.c -o design_float
	echo "********start to run design_float.exe******"
	design_float.exe
	echo "********end to run design_float.exe******"

	gcc design_overflow.c -o design_overflow
	echo "********start to run design_overflow.exe******"
	design_overflow.exe
	echo "********end to run design_overflow.exe******"

	gcc design_odd_check.c -o design_odd_check
	echo "********start to run design_odd_check.exe******"
	design_odd_check.exe
	echo "********end to run design_odd_check.exe******"
all:

	gcc design_code.c -o design_code
	echo "********start to run design_code.exe******"
	design_code.exe
	echo "********end to run design_code.exe******"

	gcc veri_float.c -o veri_float
	echo "********start to run veri_float.exe******"
	veri_float.exe
	echo "********end to run veri_float.exe******"

	gcc design_overflow.c -o design_overflow
	echo "********start to run design_overflow.exe******"
	design_overflow.exe
	echo "********end to run design_overflow.exe******"

	gcc design_odd_check.c -o design_odd_check
	echo "********start to run design_odd_check.exe******"
	design_odd_check.exe
	echo "********end to run design_odd_check.exe******"

clean:
	del -f *.exe
